version: '3.8'

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: divar_fastapi
    container_name: fastapi_app
    command: ["uvicorn", "fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      - ../.env:/app/.env
      - ../logs:/app/logs
    env_file:
      - ../.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
